### ISSUE TITLE
the credated BAM file cannot create index

### ISSUE THREAD

**Issue by SJW-Danny** [AntonJMLarsson/stitcher.py#2]
Hi! AntonJMLarsson:
  I'm a graduate student in CHINA. I'm shocked by your ideas of Smart-seq3, and the pipeline of RNA molecular reconstruction is also powerful.
  BUT when I finished the stitcher.py script, the credated BAM file cannot create index.
  That's the error:
```
     $ samtools index zUMI_stitcher.bam 
     [E::hts_idx_push] Unsorted positions on sequence #1: 3466550 followed by 3365641
     samtools index: failed to create index for "zUMI_stitcher.bam "
```

  AND that's my script:
```
#gtf to json
python gtf_to_json.py  -g /path/GRCm38/release93/Mus_musculus.GRCm38.93.gtf -d Mus_musculus.GRCm38.93.db -j Mus_musculus.GRCm38.93.json -t 2
#test
python stitcher.py --input /path/Smartseq3WTC.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam \
--isoform Mus_musculus.GRCm38.93.json \
--g /path/GRCm38/release93/Mus_musculus.GRCm38.93.gtf --t 20 --contig 1 \
--cells barcodes.txt --o zUMI_stitcher.bam
```

Looking forward to your help!
THANK!

**Comment by AntonJMLarsson** [comment]
Hello,

try sorting the bam file first with 
`samtools sort zUMI_stitcher.bam -o zUMI_stitcher_sorted.bam `

Hope this helps.
Best,
Anton

**Comment by SJW-Danny** [comment]
Thanks a lot! A great help!

Danny

**Comment by AntonJMLarsson** [comment]
Hurray! Happy to help!
